version: '3.3'

services:
  lb:
    image: khaledalissa/lb:v2
    depends_on: 
      - webapp
    environment:
      - PROXY_UPSTREAM
    ports:
      - 9000:80

  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data

  alpine:
    image: alpine:latest
    stdin_open: true
    tty: true
    command: sh

  webapp:
    image: jfahrer/demo_web_app:latest
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - pg 

volumes:
  pg-data: